import type { Metadata } from 'next'
import {
  Geist as loadGeist,
  Geist_Mono as loadGeistMono,
} from 'next/font/google'
import './globals.css'

const geistSans = loadGeist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
})

const geistMono = loadGeistMono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      lang="en"
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  )
}
